services:
  web-api:
    build: .
    ports:
      - "127.0.0.1:80:8080"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - broker

  broker:
    image: redis@sha256:858f009f9709ce576febc734aa78b8f6d624b82571f9ddb6bda4377c833b3499
    command: redis-server --requirepass ${REDIS_PASSWORD}
